name: life_frame
description: "A picture of your life, one day at a time"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  flutter_dotenv: ^5.1.0
  
  get: ^4.6.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  image_picker: ^1.1.2 
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  media_scanner: ^2.1.0
  device_info_plus: ^10.1.0
  gal: 2.3.1
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - .env
  
  fonts:
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/PeaceSans.ttf
