name: life_frame
description: "A picture of your life, one day at a time"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  image_picker: ^1.1.2 
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1
  media_scanner: ^2.1.0
  device_info_plus: ^11.4.0
  gal: 2.3.1
  flutter_local_notifications: ^19.2.1
  native_exif: ^0.6.2
  camera: ^0.11.1
  path: ^1.9.1
  image: ^4.5.4
  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  fonts:
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/PeaceSans.ttf
